- name: set the auto_prepend_file
  copy:
    dest: /etc/php/7.0/cli/conf.d/30-phpdump.ini
    content: "auto_prepend_file = \"/var/phpdump/prepend.php\""
  become: true

- name: create prepend file
  template:
    src: prependFile.php.j2
    dest: /var/phpdump/prepend.php
  become: true
  notify:
  - restart apache